###
POST http://localhost:4000/api/getjson
Content-Type: application/json

{
    "authors":["Alberto Verdejo"],
    "filters":{
    "checkInproceedings": true,
    "checkArticles": true,
    "checkIncollections": true,
    "checkSchoolar": false,
    "checkGGS": false,
    "checkCore": false,
    "checkScopus": false,
    "checkJRC": true,
    "mail": "franga06@ucm.es",
    "pass":"GAFITAS99",
    "initYear": 1900,
    "endYear": 2050
    }
}

###
POST http://localhost:4000/api/getjsonsanitize
Content-Type: application/json


{
    "authors":[{"author": "Adrian Riesco 001", "link": "https://dblp.org/pid/35/4359.html"}],
    "filters":{
    "checkInproceedings": true,
    "checkArticles": true,
    "checkIncollections": true,
    "checkSchoolar": false,
    "checkGGS": false,
    "checkCore": false,
    "checkScopus": false,
    "checkJCR": true,
    "mail": "franga06@ucm.es",
    "pass":"GAFITAS99",
    "initYear": 1900,
    "endYear": 2050
    }
}


###
POST http://localhost:4000/api/getjsonsanitize
Content-Type: application/json

[{"author": "Narciso Martí-Oliet", "link": "https://dblp.org/pid/34/4176.html"}]

###
POST http://localhost:4000/api/getjson
Content-Type: application/json

["alberto verdejo"]
###
POST http://localhost:5001/tfg-web-scrapping/us-central1/app/api/getjson
Content-Type: application/json

["narciso garcia santos"]

###
POST http://localhost:5001/tfg-web-scrapping/us-central1/app/api/getjsonsanitize
Content-Type: application/json

[{"author": "enrique martin-martin", "link": "https://dblp.org/pid/15/7982.html"}]


###

POST http://localhost:4000/api/getjsonsanitize
Content-Type: application/json

[{"author": "Alberto Verdejo", "link": "https://dblp.org/pid/70/253.html"},{"author": "Adrian Riesco 001", "link": "https://dblp.org/pid/35/4359.html"}]

###
POST https://us-central1-tfg-web-scrapping.cloudfunctions.net/app/api/getjson
Content-Type: application/json

["alberto verdejo"]

###
POST https://us-central1-tfg-web-scrapping.cloudfunctions.net/app/api/getjsonsanitize
Content-Type: application/json

[{"author": "Alberto Verdejo", "link": "https://dblp.org/pid/70/253.html"},{"author": "Adrian Riesco 001", "link": "https://dblp.org/pid/35/4359.html"},{"author": "Isabel Pita", "link": "https://dblp.org/pid/35/2414.html"} ]


// front ubicacion